### ISSUE TITLE
ISVA(Internal) -001 After clicking the "Request OTP" button, the page eventually redirects  to an error page.

### ISSUE THREAD

**Issue by niharaabeywardhana** [niharaabeywardhana/CIAM-ISVA-internal-SSO--Ncinga#1]
### Description
#
**Authentication Method Selection Screen**:

 After clicking the "Request OTP" button, the page eventually redirects  to an error page.

###  Step to Reproduce
#
1. Login with valid username and password
2. Navigates to the two factor authenthication page
3. Click request OTP button
4. Navigate to the OTP entering page

### Expected Result 
#
 After clicking the "Request OTP" button, the page eventually redirects  to "OTP Entering Screen".

### Actual Result (23/09/2024)
#
The page navigates to an error screen when clicking the "Request OTP" button on the Authentication method selection page

![Screenshot (1681)](https://github.com/user-attachments/assets/b4f7f5e4-da4d-4045-a492-0b0dbd70321e)

![Screenshot (1682)](https://github.com/user-attachments/assets/a243529b-8642-4868-adfa-a982f9e710c7)

[](https://github.com/user-attachments/assets/9434c855-d30d-43fb-a5c3-a66ff2fb744f)

**Comment by supunncinga** [comment]
There was a firewall issue and it has been fixed now.
