### ISSUE TITLE
ISVA(Internal) -010 Email format -User Name is not mentioned in the e-mail

### ISSUE THREAD

**Issue by niharaabeywardhana** [niharaabeywardhana/CIAM-ISVA-internal-SSO--Ncinga#10]
### Description
#
Email format -User Name is not mentioned in the e-mail

###  Step to Reproduce
#
1. Logged into ISVA portal through username and password
2. Check OTP which received to the email

### Expected Result 
#
The email format should be display as below
"Hello “<First name>”,
Your Security Code for completing SSO verification #Ref# is: ##otp##
Do not share this code with anyone.
Thank you,
Commercial Bank PLC
Disclaimer: This email and any files transmitted with it are confidential and intended solely
for the use of the individual or entity to whom they are addressed.

### Actual Result (26/09/2024)
#
Hello,

Your Security Code for completing SSO verification is 3628-864255.
Do not share this code with anyone.

Thank you, Commercial Bank PLC.

Thank you,
 OTP Test

First name is not mentioned in the e-mail.
![Screenshot (1688)](https://github.com/user-attachments/assets/3d722e23-bc51-4bc6-ad8e-a30b12c76296)

**Comment by supunncinga** [comment]
This is fixed
