### ISSUE TITLE
ISVA(Internal) -012 - Soft Token - Time Out

### ISSUE THREAD

**Issue by pasanwee99** [niharaabeywardhana/CIAM-ISVA-internal-SSO--Ncinga#12]
### Description
#
Soft Token Time Out Not working 

### Test Env - DEV & UAT 
       26-sep-2024

###  Step to Reproduce
#
1.Navigate to the Two - Factor - Authentication view
2. Click Soft Token Option
3. Open IBM app using your mobile device
4.Enter Time Out Soft Token 

### Expected Result 
#
When enter time out soft token user cant navigate to landing page 
User should display "Invalid Pass Code. Please Try Again. - @ Attempts Remaining " when enter time out soft token .

### Actual Result (26/09/2024)
#
When enter time out soft token user can navigate to landing page without check time out condition

**Comment by supunncinga** [comment]
So the soft tokens time out ticking happens on the mobile device where the authenticator app is running.

**Comment by pasanwee99** [comment]
### Test Result
The soft token is only valid for 30 seconds in the IBM Verify mobile app. If the soft token is entered after it's expired , it still allows the user to login.

**Comment by pasanwee99** [comment]
### Test Result
The soft token is only valid for 30 seconds in the IBM Verify mobile app. If the soft token is entered after it's expired , it still allows the user to login.

**Comment by supunncinga** [comment]
@pasanwee99 this is fixed in the UAT. (this is a configurable value and does not need a release)

**Comment by pasanwee99** [comment]
check in UAT - (2024-OCT-09)
Working properly. 
### Test Result
The soft token is only valid for 30 seconds. Now system not get valid soft token after passed the time count.

![image](https://github.com/user-attachments/assets/56940ef2-49d3-4a18-b7ea-af2636258e3e)
