### ISSUE TITLE
ISVA(Internal) -013  The system is incorrectly handling the expired OTP scenario when an incorrect OTP is entered after expiration.

### ISSUE THREAD

**Issue by niharaabeywardhana** [niharaabeywardhana/CIAM-ISVA-internal-SSO--Ncinga#13]
### Description
#

The system is incorrectly handling the expired OTP scenario when an incorrect OTP is entered after expiration. It should display "OTP expired" in both cases.

###  Step to Reproduce
#
1. Login with valid username and password
2. Click request OTP button in the two factor authentication page
3. Navigate to the "OTP entering" Screen
4. Wait for 2 minutes without entering the OTP.
5. Enter the valid OTP after 2 minutes after it has expired.
6. Without requesting a new OTP, enter an incorrect OTP(not the one that was sent.)
7. Check the error message.
8. Again  Without requesting a new OTP, enter an incorrect OTP.
9.Check the error message.

### Expected Result 
#

The system should not display "OTP expired" message when entering invalid OTP after expiration. 

### Actual Result (27/09/2024)
#
The system shows "OTP expired" message for the invalid OTP after expiration.As well system shows some wrong error message after maximum OTP  is exceeded.

![Screenshot (1692)](https://github.com/user-attachments/assets/f78cf788-1e1d-4d87-97a8-f5887a539186)

Uploading issue 13.mp4…

**Comment by supunncinga** [comment]
This is fixed
