### ISSUE TITLE
ISVA(Internal) -016 After three failed OTP attempts, the system should not display a correct error message.

### ISSUE THREAD

**Issue by niharaabeywardhana** [niharaabeywardhana/CIAM-ISVA-internal-SSO--Ncinga#16]
### Description
#

After three failed OTP attempts, the system is not display a correct error message.

###  Step to Reproduce
#

1.Navigate to the “Entering the OTP “ screen.
2.Enter an invalid OTP in the input field (attempt 1).
3.Enter another invalid OTP in the input field (attempt 2).
4.Enter a different invalid OTP in the inputfield (attempt 3).

### Expected Result 
#
After three failed attempts, the system should lock and display a message.

### Actual Result (30/09/2024)
#
After three failed attempts, the system is not display a correct message.
![Screenshot (1701)](https://github.com/user-attachments/assets/9bbe3f57-1977-4a08-8f4a-69a3362bc41a)

https://github.com/user-attachments/assets/088a3224-83cf-48d9-ab4e-41d4bcc80201

**Comment by supunncinga** [comment]
This is fixed.
