### ISSUE TITLE
ISVA(Internal) -017 After the third incorrect OTP attempt, the  OTP input boxes are not disabled.

### ISSUE THREAD

**Issue by niharaabeywardhana** [niharaabeywardhana/CIAM-ISVA-internal-SSO--Ncinga#17]
### Description
#

Verify that the OTP input boxes are disabled after the user has made three incorrect attempts to enter the OTP.

###  Step to Reproduce
#
1.Navigate to the “Entering the OTP “ screen.
2.Enter an invalid OTP in the input field (attempt 1).
3.Enter another invalid OTP in the input field (attempt 2)
4.Enter a different invalid OTP in the input field (attempt 3).
5.Verify Input Boxes Status:After the third failed attempt, check the status of the OTP input boxes.

### Expected Result 
#

After the third incorrect OTP attempt, the OTP input boxes should be disabled, preventing any further input.

### Actual Result (30/09/2024)
#
After the third incorrect OTP attempt, the OTP input boxes are not disabled.

https://github.com/user-attachments/assets/1d9175eb-b9e4-443e-b558-c7a412c46104

**Comment by supunncinga** [comment]
This is fixed
