### ISSUE TITLE
ISVA(Internal) -020  After account lockout period(15 minutes), users can enter invalid OTP and receive long error message instead of proper error message.

### ISSUE THREAD

**Issue by niharaabeywardhana** [niharaabeywardhana/CIAM-ISVA-internal-SSO--Ncinga#19]
### Description
#

After account lockout period(15 minutes), users can enter invalid OTP and receive long error message instead of proper error message.

###  Step to Reproduce
#

1.Attempt to log in and enter 3 consecutive invalid OTPs.
2.After the 3rd invalid attempt, observe that the account is locked for 15 minutes, as expected.
3.Wait for the 15-minute lockout period to expire.
4.After 15 minutes, enter another invalid OTP attempt.
5.Observe the system's behavior and the message returned.

### Expected Result 
#

After 15 minutes, the account lockout should be released, and the user should be allowed to attempt logging in with a valid OTP again.
The system should give a clear and concise error message if another invalid OTP is entered after the lockout.
The user should be allowed 3 new attempts after the lockout.

### Actual Result (10/07/2024)
#
After 15 minutes, when the user enters an invalid OTP again, the system displays an unusually long and unformatted error message instead of properly handling the invalid attempt.

https://github.com/user-attachments/assets/31fb311a-8091-476e-911a-0afa3acfe7a8

![Screenshot (1801)](https://github.com/user-attachments/assets/7f6e41af-7b6d-4957-8cb4-0927fcb4a338)

**Comment by supunncinga** [comment]
@niharaabeywardhana please align with  the BA NCINGA/Combank and get the generic error message format for such incidents. Something like "Internal Error please try again" or "Something went wrong!! Please refresh the page to start back"
