### ISSUE TITLE
ISVA(Internal) -002 Once logged into the system with valid credentials, in the "Scan QR Code to Connect to your Account" screen user id display as null

### ISSUE THREAD

**Issue by niharaabeywardhana** [niharaabeywardhana/CIAM-ISVA-internal-SSO--Ncinga#2]
### Description
#
**Scan QR Code to Connect to your Account screen**:

Once logged into the system with valid credentials, in the "Scan QR Code to Connect to your Account" screen user id display as null

###  Step to Reproduce
#
1. Login with valid username and password
2. Scan QR and install IBM security verify app
3. Click next button
4. Navigates to the second QR code screen

### Expected Result 
#
Null word should be display as logged in user id in the "scan QR code to conncet to your account" screen

### Actual Result (23/09/2024)
#
The logged in user display as null in the "scan qr code to conncet to your account page 
![Screenshot (1632)](https://github.com/user-attachments/assets/23429cdf-518b-4987-88c4-ab966a36acfd)

https://github.com/user-attachments/assets/df7bf5e1-a433-4961-a96e-1c3bc0533191

**Comment by supunncinga** [comment]
This is fixed
