### ISSUE TITLE
ISVA(Internal) -004 The countdown timer is not displaying on the account lockout screen after the maximum number of login has been exceeded.

### ISSUE THREAD

**Issue by niharaabeywardhana** [niharaabeywardhana/CIAM-ISVA-internal-SSO--Ncinga#4]
### Description
#

The countdown timer is not displaying on the account lockout screen after the maximum number of logins has been exceeded.

###  Step to Reproduce
#

1.Login with invalid login credentials(user ID/Password) multiple times.
2. After account lockout ,Check time countdown working correctly

### Expected Result 
# 
The countdown timer should function correctly on the account lockout screen.

### Actual Result (23/09/2024)
# 
The countdown timer is not functioning correctly on the lockout page. Only showing maximum lockout time.

![Screenshot (1685)](https://github.com/user-attachments/assets/01343659-e1d3-4c50-a528-fc772480a448)

https://github.com/user-attachments/assets/60fee093-c06b-41af-95f9-1ef5be0f020a

**Comment by supunncinga** [comment]
This is the default behavior, ISVA can't determine remaining time for the lockout expiration as lockout mechanism is an Active Directory functionality.
