### ISSUE TITLE
ISVA(Internal) -007  The entered OTP code is not properly aligned in the boxes while typing

### ISSUE THREAD

**Issue by niharaabeywardhana** [niharaabeywardhana/CIAM-ISVA-internal-SSO--Ncinga#7]
### Description
#

The entered OTP code is not properly aligned in the boxes while typing

###  Step to Reproduce
#
1. Login with valid username and password
2. Navigate to the Entering OTP screen
3. Enter given OTP six digit code

### Expected Result 
#
The  OTP six digit code should be filled on the center of the box.

### Actual Result (25/09/2024)
#
The  OTP six digit code are  filled to the left side of the box ,when clear the boxes back button not user friendly 
![Screenshot (1686)](https://github.com/user-attachments/assets/ed5b0cf1-a9ea-45fb-ab04-a04b2a946a9c)

https://github.com/user-attachments/assets/e6867f67-4bb2-4e52-8066-bf3c11cbc7f7

**Comment by supunncinga** [comment]
This is fixed
