### ISSUE TITLE
ISVA(Internal) -008 OTP Field Accept Spaces or Leading Whitespaces

### ISSUE THREAD

**Issue by niharaabeywardhana** [niharaabeywardhana/CIAM-ISVA-internal-SSO--Ncinga#8]
### Description
#

OTP Field Accept Spaces or Leading Whitespaces

###  Step to Reproduce
#
1.Navigate to the OTP input screen.
2. Enter an OTP with spaces between digits.
3. Enter an OTP with leading and trailing spaces.

### Expected Result 
#
The OTP field should not accept an input with spaces.

### Actual Result (26/09/2024)
#
The OTP field accept an input with spaces.

https://github.com/user-attachments/assets/674815d3-280f-4117-911d-5176cee4051e

**Comment by supunncinga** [comment]
This is fixed
