### ISSUE TITLE
ISVA(Internal) -009 Verify that the cursor automatically positions in the first box of the OTP input field.

### ISSUE THREAD

**Issue by niharaabeywardhana** [niharaabeywardhana/CIAM-ISVA-internal-SSO--Ncinga#9]
### Description
#

Verify that the cursor automatically positions in the first box of the OTP input field.

###  Step to Reproduce
#
1.Navigate to the OTP input screen.
2.Observe the initial position of the cursor after the OTP screen is fully loaded.
3.Manually click outside of the OTP input field, then click back into the field.
4.Refresh the OTP input screen and observe the cursor position again after the screen reloads.

### Expected Result 
#
The cursor should automatically position itself in the first box of the OTP input field as soon as the screen loads. Upon refreshing the screen, the cursor should automatically return to the first box of the OTP input field without requiring any user interaction.

### Actual Result (26/09/2024)
#
The cursor should not automatically position itself in the first box of the OTP input field as soon as the screen loads. Upon refreshing the screen, the cursor should not automatically return to the first box of the OTP input field without requiring any user interaction.

https://github.com/user-attachments/assets/990634d7-3824-4f94-b8be-13f8b73b4413

**Comment by supunncinga** [comment]
This is fixed
